_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 50
                - 53
                - 55
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 50
                - 53
                - 55
                - 103
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.8
            "6": 4.48.3
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
data:
    value:
        _target_: src.data.datamodule.ActuatorDataModule
        accel_axis_for_torque: Acc_Y
        batch_size: 32
        dataset_configs:
            - csv_file_path: data/synthetic_raw/synthetic_actuator_data_mass_0.csv
              inertia: 0.01
            - csv_file_path: data/synthetic_raw/synthetic_actuator_data_mass_1.csv
              inertia: 0.015
            - csv_file_path: data/synthetic_raw/synthetic_actuator_data_mass_2.csv
              inertia: 0.02
        fallback_sampling_frequency: 100
        global_train_ratio: 0.7
        global_val_ratio: 0.15
        gyro_axis_for_ang_vel: Gyro_Z
        num_workers: 4
        radius_accel: 0.2
        radius_load: 0.3
        seed: 42
        target_name: tau_measured
debug:
    value: false
evaluation_mode:
    value: lomo_cv
model:
    value:
        _target_: src.models.model.ActuatorModel
        gru_dropout: 0.1
        gru_hidden_dim: 128
        gru_num_layers: 2
        k_spring: 0
        kd_phys: 0
        kp_phys: 0
        learning_rate: 0.001
        loss_diff_weight: 0.1
        mlp_activation: relu
        mlp_dropout: 0.1
        mlp_hidden_dims:
            - 64
            - 128
            - 64
        mlp_use_batch_norm: true
        model_type:
            name: gru
        theta0: 0
        use_residual: false
        warmup_epochs: 1
        weight_decay: 1e-06
outputs_dir:
    value: /home/daniel/workspace/actuator_modeling/outputs/2025-05-28/15-02-32
seed:
    value: 42
train:
    value:
        accelerator: auto
        batch_size: 32
        callbacks:
            early_summary: false
            learning_rate_monitor: true
            test_prediction_plotter: true
        checkpointing:
            filename: best_model-{epoch:02d}-{val_rmse_epoch:.4f}
            mode: min
            monitor: val_rmse_epoch
            save_top_k: 1
        data: ../data/actuator_data.yaml
        deterministic_trainer: true
        devices: 1
        early_stopping:
            active: true
            min_delta: 0.0001
            mode: min
            monitor: val_rmse_epoch
            patience: 20
            stopping_threshold: null
            verbose: true
        gradient_clip_algorithm: norm
        gradient_clip_val: 5
        learning_rate: 0.001
        log_frequency: 50
        max_epochs: 200
        model: ../model/mlp.yaml
        num_workers: 4
        patience: 20
        precision: 32-true
        val_check_interval: 1
        wandb:
            project_name: actuator-modeling
        weight_decay: 1e-06
wandb:
    value:
        active: true
        entity: ""
        group_suffix: initial_tests
        name_suffix: debug
        project: actuator_modeling_gru_v2
        watch_log_freq: 100
work_dir:
    value: /home/daniel/workspace/actuator_modeling
