debug: false
seed: 42 # Global random seed

evaluation_mode: "global" # "global" or "lomo_cv"

defaults:
  - _self_ # Inherit from this file itself
  - data: default  # Use synthetic data for training
  - model: default # This will load configs/model/default.yaml (which itself defaults to GRU type)
  - train: default

# Workspace and output directory structure
# these paths are relative to the output directory that Hydra creates for each run
# (e.g. outputs/YYYY-MM-DD/HH-MM-SS/)
work_dir: ${hydra:runtime.cwd} # The original CWD; for accessing source data, etc.
outputs_dir: ${hydra:runtime.output_dir} # The directory Hydra creates for this run

# --- Experiment Tracking (Example: WandB) ---
wandb:
  active: true # set to false to disable wandb
  project: "actuator_modeling_gru_v2" # Your WandB project name
  entity: "" # Your WandB entity (username or team), optional
  name_suffix: "pure_gru_loss_diff_max_vel" # Optional suffix for run names
  group_suffix: "initial_tests" # Optional suffix for wandb groups
  watch_log_freq: 100
  # tags: ["${model.model_type}", "lomo_cv"]
  # log_model: "all" # 'all', 'best', or false
